version: "3"
services:
  mysql:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_HOST: localhost
      MYSQL_DATABASE: mydb
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    expose:
      - 3308
    networks:
            - app-tier
    volumes:
      - /var/lib/mysql
      - ./mysql/migrations:/docker-entrypoint-initdb.d
    restart: unless-stopped

networks:
    app-tier:
        driver: bridge