version: "3"
services:
  db:
    image: mysql:5.7
    shm_size: 2gb
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=node_test
      - MYSQL_USER=node
      - MYSQL_PASSWORD=node
    ports:
      - '3308:3307'
    volumes:
      - '.:/mysql/migrations'
      - './mysql/migrations:/var/lib/mysql'
    healthcheck:
      test: 'mysqladmin ping -h localhost -proot'
      interval: 30s
      timeout: 30s
      retries: 3

networks:
    app-tier:
        driver: bridge